apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-sec
  namespace: bags-luggage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: mongo-sec
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: bags-luggage/mongodb
        property: username
    - secretKey: password
      remoteRef:
        key: bags-luggage/mongodb
        property: password