apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: bags-luggage
  annotations:
    # From `terraform output external_secrets_role_arn` in terraform_eks/main
    eks.amazonaws.com/role-arn: arn:aws:secretsmanager:ap-south-1:264284392886:secret:bags-luggage/mongodb-VgpWc3
    argocd.argoproj.io/sync-wave: "-2"