apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: bags-luggage
  annotations:
    # From `terraform output external_secrets_role_arn` in terraform_eks/main
    eks.amazonaws.com/role-arn: <EXTERNAL_SECRETS_ROLE_ARN>
    argocd.argoproj.io/sync-wave: "-2"